### ISSUE TITLE
CrazyRadio PA hardware bricked by flasher

### ISSUE THREAD

**Issue by ad0nis** [BastilleResearch/keysniffer#1]
I just received a new CrazyRadio PA in the mail, and attempted to follow this tutorial to flash it today, and ran into the following problem:

root@kali:~/tools/keysniffer/nrf-research-firmware$ make
sdcc --model-large --std-c99 -c src/main.c -o bin/main.rel
sdcc --model-large --std-c99 -c src/usb.c -o bin/usb.rel
sdcc --model-large --std-c99 -c src/usb_desc.c -o bin/usb_desc.rel
sdcc --model-large --std-c99 -c src/radio.c -o bin/radio.rel
sdcc --xram-loc 0x8000 --xram-size 2048 --model-large bin/main.rel bin/usb.rel bin/usb_desc.rel bin/radio.rel -o bin/dongle.ihx
objcopy -I ihex bin/dongle.ihx -O binary bin/dongle.bin
objcopy --pad-to 26622 --gap-fill 255 -I ihex bin/dongle.ihx -O binary bin/dongle.formatted.bin
objcopy -I binary bin/dongle.formatted.bin -O ihex bin/dongle.formatted.ihx

root@kali:~/tools/keysniffer/nrf-research-firmware$ sudo make install
./prog/usb-flasher/usb-flash.py bin/dongle.bin
[2016-08-22 11:56:57.790]  Looking for a compatible device that can jump to the Nordic bootloader
[2016-08-22 11:56:57.803]  Looking for a device running the Nordic bootloader
[2016-08-22 11:56:59.788]  Writing image to flash
Traceback (most recent call last):
  File "./prog/usb-flasher/usb-flash.py", line 101, in <module>
    dongle.read(0x81, 64, usb_timeout)
  File "/usr/lib/python2.7/dist-packages/usb/core.py", line 659, in read
    intf.bInterfaceNumber,
AttributeError: 'NoneType' object has no attribute 'bInterfaceNumber'
Makefile:27: recipe for target 'install' failed
make: **\* [install] Error 1

Now, when plugging the device back into my system, it isn't even registered in lsusb, so it appears that the dongle has been bricked by the flasher included in this repo. I'll be attempting to fix it with a Teensy later on today if I can find one in my toolkit.

**Comment by ad0nis** [comment]
I managed to recover my device with the use of a BusPirate and these instructions:
https://wiki.bitcraze.io/projects:crazyradio:spi_programming
